name: Java CI

on:
  push:
    branches:
      - main   # Replace with the branch you want to trigger the workflow
  pull_request:
    branches:
      - main   # Optional: Run tests on pull requests as well

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Replace with your Java version, e.g., 8, 11, 17, etc.
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Java Unit tests
        run: mvn test